#!/bin/bash

sed '1,/^# # DATA # #$/d' $0 |
	rofi -i -dmenu -config ~/.config/rofi/config-emoji.rasi |
	cut -f 1 | tr -d '\n' | wl-copy

exit
# # DATA # #
⊂(◉‿◉)つ	(acid)
(ㆆ _ ㆆ)	(afraid)
α	(alpha)
☜(⌒▽⌒)☞	(angel)
•`_´•	(angry)
⤜(ⱺ ʖ̯ⱺ)⤏	(arrowhead)
	(apple)
(‿|‿)	(ass)/(butt)
•͡˘㇁•͡˘	(awkward)
/|\ ^._.^ /|\	(bat)
ʕ·͡ᴥ·ʔ﻿		(bear)/(koala)
ʕノ•ᴥ•ʔノ ︵ ┻━┻	(bearflip)
ʕっ•ᴥ•ʔっ	(bearhug)
∵	(because)/(since)
β	(beta)
❤	(bigheart)
₿	(bitcoin)
0__#	(blackeye)
( 0 _ 0 )	(blubby)
(˵ ͡° ͜ʖ ͡°˵)	(blush)
┌( ͝° ͜ʖ͡°)=ε/̵͇̿̿/’̿’̿ 	(bond)/(007)
( . Y . )	(boobs)
(-_-)	(bored)
( •͡˘ _•͡˘)ノð 	(bribe)
( ˘ ³˘)ノ°ﾟº❍｡	(bubbles)
ƸӜƷ	(butterfly)
(= ФェФ=)	(cat)
( ͡° ᴥ ͡°)﻿	(catlenny)
✔	(check)
※\(^o^)/※	(cheer)
╭(ʘ̆~◞౪◟~ʘ̆)╮	(chubby)
(͡ ° ͜ʖ ͡ °)	(claro)
ヽ༼ ຈل͜ຈ༼ ▀̿̿Ĺ̯̿̿▀̿ ̿༽Ɵ͆ل͜Ɵ͆ ༽ﾉ	(clique)/(gan)/(squad)
☁	(cloud)
♣	(club)
c[_]	(coffee)/(cuppa)
⌘	(cmd)/(command)
(•_•) ( •_•)>⌐■-■ (⌐■_■)	(cool)/(csi)
©	(cop)/(c)
ԅ(≖‿≖ԅ)	(creep)
ƪ(ړײ)‎ƪ​​	(creepcute)
( ✜︵✜ )	(crim3s)
†	(cross)
(╥﹏╥)	(cry)
( ╥﹏╥) ノシ	(crywave)
(｡◕‿‿◕｡)	(cute)
⚀	(d1)
⚁	(d2)
⚂	(d3)
⚃	(d4)
⚄	(d5)
⚅	(d6)
ヽ( •_)ᕗ	(dab)
(ᕗ ͠° ਊ ͠° )ᕗ	(damnyou)
ᕕ(⌐■_■)ᕗ ♪♬	(dance)
x⸑x 	(dead)/(dealwithit)
(⌐■_■)	(dwi)
Δ	(delta)
(︶︹︶)	(depressed)
☉ ‿ ⚆	(derp)
♦	(diamond)
d[-_-]b	(dj)
(◕ᴥ◕ʋ)	(dog)
$	(dollar)
[̲̅$̲̅(̲̅ιο̲̅̅)̲̅$̲̅] 	dollarbill)/($) 
(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄	(dong)
ヽ༼ຈل͜ຈ༽ﾉ	(donger)
(- ʖ̯-)	(dontcare)/(idc)
ヽ(｀Д´)ﾉ	(do not want)/(dontwant)
<(^_^)>	(dope)	« (<<) 	» (>>) 
𝄫	(doubleflat)
𝄪	(doublesharp)
┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻	(doubletableflip)
↓	(down)
(・3・)	(duckface)
ᕕ(╭ರ╭ ͟ʖ╮•́)⊃¤=(————-	(duel)
(≧︿≦)	(duh)
¯\(°_o)/¯	(dunno)
(-(-_-(-_(-_(-_-)_-)-_-)_-)_-)-)	(eeriemob)
… 	(ellipsis)/(...) 
– 	(emdash)/(--) 
☆	(emptystar)
△	(emptytriangle)/(t2)
(҂◡_◡) ᕤ	(endure)
✉︎	(envelope)/(letter)
ɛ	(epsilon)
€	(euro)
ψ(｀∇´)ψ	(evil)
(͠≖ ͜ʖ͠≖)	(evillenny)
(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧	(excited)
(⌐■_■)︻╦╤─ (╥﹏╥)	(execution)
(╯°□°)╯︵ ʞooqǝɔɐɟ  	(facebook)
(－‸ლ)	(facepalm)
вєωαяє, ι αм ƒαη¢у!	(fancytext)
(ˆ⺫ˆ๑)<3	(fart)
(ง •̀_•́)ง	(fight)
| (• ◡•)|	(finn)
<"(((<3	(fish)
卌	(5)/(five)
⅝ (five/eight)/	5/8)
♭	(flat)/(bemolle)
ᕙ(`▽´)ᕗ	(flexing)
ǝןqɐʇ ɐ ǝʞıן ǝɯ dıןɟ	(fliptext)
(ノ ゜Д゜)ノ ︵ ǝןqɐʇ ɐ ǝʞıן ʇxǝʇ dıןɟ	(fliptexttable)
┬─┬﻿ ︵ /(.□. \)	(flipped)/(heavytable) 
(✿◠‿◠)	(flower)/(flor)
✿	(f)
─=≡Σ((( つ◕ل͜◕)つ	(fly)
(╯°□°)╯︵ ┻━┻ ︵ ╯(°□° ╯)	(friendflip)
(ღ˘⌣˘ღ)	(frown)
୧༼ಠ益ಠ╭∩╮༽	(fuckoff)/(gtfo)
┌П┐(ಠ_ಠ)	(fuckyou)/(fu)
ಠ_ರೃ	(gentleman)/(sir)/(monocle)
= _ =	(ghast)
༼ つ ╹ ╹ ༽つ	(ghost)
(´・ω・)っ由	(gift)/(present)
༼ つ ◕_◕ ༽つ	(gimme)
(•-•)⌐	(givemeyourmoney)
(*・‿・)ノ⌒*:･ﾟ✧	(glitter)
(⌐ ͡■ ͜ʖ ͡■)	(glasses)
( ͡° ͜ʖ ͡°)ﾉ⌐■-■	(glassesoff)
(ﾉ☉ヮ⚆)ﾉ ⌒*:･ﾟ✧	(glitterderp)
(_゜_゜_)	(gloomy)
(з๏ε)	(goatse)
(☞ﾟ∀ﾟ)☞	(gotit)
( ´◔ ω◔`) ノシ	(greet)/(greetings)
︻╦╤─	(gun)/(mg)
༼つಠ益ಠ༽つ ─=≡ΣO))	(hadouken)
☭	(hammerandsickle)/(hs)
☜	(handleft)/(hl)
☞	(handright)/(hr)
٩(^‿^)۶	(haha)
٩( ๑╹ ꇴ╹)۶	(happy)
ᕕ( ᐛ )ᕗ	(happygarry)
♥	(h)/(heart) 
<3	(heart ASCII) 
(ʘ‿ʘ)╯	(hello)/(aloha)/(bye)
\(°Ω°)/	(help)
._.)/\(._.	(highfive)
( ｀皿´)｡ﾐ/	(hitting)
(づ｡◕‿‿◕｡)づ	(hug)/(hugs)
┐｜･ิω･ิ#｜┌ 	(iknowrigh)/(ikr)
୧(▲ᴗ▲)ノ	(illuminati)
∞	(infinite)/(inf)
(っ´ω`c)♡	(inlove)
∫	(int)
ଘ(੭*ˊᵕˋ)੭* ̀ˋ ɪɴᴛᴇʀɴᴇᴛ	(internet)
‽	(interrobang)
(❍ᴥ❍ʋ)	(jake)
(¬,‿,¬)	(kappa)
≧◡≦	(kawaii)
┬┴┬┴┤Ɵ͆ل͜Ɵ͆ ༽ﾉ	(keen)
~\(≧▽≦)/~	(kiahh 
(づ ￣ ³￣)づ	(kiss)
／人◕ ‿‿ ◕人＼	(kyubey)
λ	(lambda)
_(:3」∠)_	(lazy)
/z(<-) ←	(left)
( ͡° ͜ʖ ͡°)	(lenny)
[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]	(lennybill)
(ง ͠° ͟ʖ ͡°)ง	(lennyfight)
(ノ ͡° ͜ʖ ͡°ノ) ︵ ( ͜。 ͡ʖ ͜。)	(lennyflip)
( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)	(lennygang)
¯\_( ͡° ͜ʖ ͡°)_/¯	(lennyshrug)
( ಠ ͜ʖ ರೃ)	(lennysir)
┬┴┬┴┤( ͡° ͜ʖ├┬┴┬┴	(lennystalker)
ᕦ( ͡° ͜ʖ ͡°)ᕤ	(lennystrong)
╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ	(lennywizard)
███▒▒▒▒▒▒▒	(loading)
L(° O °L)	(lol)
(ಡ_ಡ)☞	(look)
ᕦ(⩾﹏⩽)ᕥ	(loud)/(noise)
♥‿♥	(love)
ʕ♥ᴥ♥ʔ	(lovebear)
꒰ ꒡⌓꒡꒱	(lumpy)
-`ღ´-	(luv)
ヽ(｀Д´)⊃━☆ﾟ. * ･ ｡ﾟ,	(magic)
(/¯◡ ‿ ◡)/¯ ~ ┻━┻	(magicflip)
\(°^°)/	(meep)
ಠ_ಠ	(meh)
\m/,(> . <)_\m/	(metal)/(rock)
ಡ_ಡ	(mistyeyes)
༼ ༎ຶ ෴ ༎ຶ༽	(monster)
♮	(natural)
┌(◉ ͜ʖ◉)つ┣▇▇▇═──	(needle)/(inject)
(⌐⊙_⊙)	(nerd)
( ͡° ͜ °)	(nice)
→_←	(no)
／人◕ __ ◕人＼	(noclue)
(っˆڡˆς)	(nom)/(yummy)/(delicious)
♫	(note)/(sing)
☢	(nuclear)/(radioactive)/(nukular)
~=[,,_,,]:3	(nyan)
@^@	(nyeh)
( º﹃º )	(ohshit)
Ω	(omega)
◕_◕	(omg)
⅛ 	(one/eight)/(1/8)
¼ 	(one/four)/(1/4)
½ 	(uno/two)/(1/2)
⅓ 	(one/three)/(1/3)
⌥	(opt)/(option)
(눈_눈)	(orly)
(◞థ౪థ)ᴖ	(ohyou)/(ou)
✌(-‿-)✌	(peace)/(victory)
(__>-	(pear)
π	(pi)
( •_•)O*¯`·.¸.·´¯`°Q(•_• )	(pingpong)
._.	(plain)
˶‾᷄ ⁻̫ ‾᷅˵)	(pleased)
(☞ﾟヮﾟ)☞	(point)
ʕ •́؈•̀)	(pooh)
(•ᴥ• )́`́'́`́'́⻍	(porcupine)
£	(pound)
(☝ ՞ਊ ՞)☝	(praise)
O=('-'Q)	(punch)
t(ಠ益ಠt)	(rage)/(mad)
(ノಠ益ಠ)ノ彡┻━┻	(rageflip)
(=^･ｪ･^=))ﾉ彡☆	(rainbowcat)
ò_ô	(really)
®	(r)
→ 	(right)/(->)  
୧༼ಠ益ಠ༽୨	(riot)
⚁	(rolldice)
(◔_◔)	(rolleyes)
✿ڿڰۣ—	(rose)
(╯°□°)╯	(run)
ε(´סּ︵סּ`)з	(sad)
ヽ༼ຈʖ̯ຈ༽ﾉ	(saddonger)
( ͡° ʖ̯ ͡°)	(sadlenny)
⅞ (seven/eight)	7/8) 
♯	(sharp)/(diesis)
╚(•⌂•)╝	(shout)
¯\_(ツ)_/¯	(shrug)
=^_^=	(shy)
Σ	(sigma)/(sum)
☠	(skull)
ツ	(smile)
☺︎	(smiley)
¬‿¬	(smirk)
☃	(snowman)
(;´༎ຶД༎ຶ`)	(sob)
ノ┬─┬ノ ︵ ( \o°o)\	(soviettableflip)
♠	(spade)
√	(sqrt)
<コ:彡	(squid)
★	(star)
ᕙ(⇀‸↼‶)ᕗ	(strong)
ε/̵͇̿̿/’̿’̿ ̿(◡︵◡)	(suicide)
∑	(sum)
☀	(sun)
(๑•́ ヮ •̀๑)	(surprised)
\_(-_-)_/	(surrender)
 o(╥﹏╥)o	(surrender2)
┬┴┬┴┤(･_├┬┴┬┴	(stalker)
 (̿▀̿‿ ̿▀̿ ̿)	(swag)
o()xxxx[{::::::::::::::::::>	(sword)
┬─┬﻿ ノ( ゜-゜ノ)	(tabledown)
(ノ ゜Д゜)ノ ︵ ┻━┻	(tableflip)
τ	(tau)
(ಥ﹏ಥ)	(tears)
୧༼ಠ益ಠ༽︻╦╤─	(terrorist)
\(^-^)/	(thanks)/(thankyou)/(ty)
⸫	(therefore)/(so)
( ͡° ͜ʖ ͡°)_/¯	(this)
⅜ (three/eight)	3/8) 
|=-(¤)-=|	(tiefighter)
(=____=)	(tired)
☜(꒡⌓꒡)	(toldyouso)/(toldyou)
ᕦ(òᴥó)ᕥ	(toogood)
™	(tm)
▲	(triangle)/(t)
⅔ (two/three)/	2/3)
┬──┬ ノ(ò_óノ)	(unflip)
↑	(up)
(๑•̀ㅂ•́)ง✧	(victory)
(ÒДÓױ)	(wat)
( * ^ *) ノシ	(wave)
Ö	(whaa)
(っ^з^)♪♬	(whistle)
(°o•)	(whoa)
ლ(`◉◞౪◟◉‵ლ)	(why)
＼(＾O＾)／	(woo)
(⊙＿⊙')	(wtf)
⊙ω⊙	(wut)
\( ﾟヮﾟ)/	(yay)
(•̀ᴗ•́)و ̑̑	(yeah)/(yes)
¥	(yen)
☯	(yinyang)/(yy)
ლ༼>╭ ͟ʖ╮<༽ლ	(youkids)/(ukids)
(屮ﾟДﾟ)屮 Y U NO	(y u n o)/(yuno)
⊹╰(⌣ʟ⌣)╯⊹	(zen)/(meditation)/(omm)
(V) (°,,,,°) (V)	(zoidberg)
[¬º-°]¬	(zombie)
(n_n)	(smile jpn)
(._.)	(uh..oh jpn)
(-_-)	(sleepy tired jpn)
(;_;)	(tears jpn)
(@_@)	(dizzy jpn)
(o_o)	(amazed jpn)
(*^*)	(astonished jpn)
(>-<)	(ouch jpn)
(^_^)	(happy jpn)
*(^o^)*	(happier jpn)
(^o^)	(glad jpn)
(x.x)	(dead jpn)
(=-=)	(bored jpn)
(*-*)	(i love it jpn)
(!_!)	(sad jpn)
(o_O)	(incredulous jpn)
(*O*)	(incredible jpn)
(O_O)	(seriously jpn)
(;O;)	(crying bad jpn)
(.o.')	(confused jpn)
(-_-;)	(i messed it up jpn)
('_')	(serious jpn)
(u_u)	(sleepy, sad jpn)
(xOx)	(nooo jpn)
(>o<)	(yuck jpn)
(-_O)	(wink jpn)
8(>-<)8	(jelaous jpn)
(9_9)	(didn't sleep jpn)
(>>)	(awry jpn)
(~o~)	(you're crazy)
(<ゝw•)☆	(ok wink)
;-;	(cry Lore)
┐('~`;)┌	(I dont know)/(idk)
